### ISSUE TITLE
Synchronize one subtitle to another?

### ISSUE THREAD

**Issue by tarzoq** [baxtree/subaligner#88]
More of a question than an issue, is it possible to use subaligner for synchronizing one subtitle to another? The subtitles would be in different languages and one already synchronized to the video. It's for a post-processing script for Bazarr that I'm working on, and in my testing I have found English subtitles to generally have the best result.

I also wanted to add that this synchronizer easily beats all the other tools available by a landslide. This will save me so much time and effort and I'm thankful that people with your expertise develop software that clueless people like me have great use for.

**Comment by baxtree** [comment]
Hi, @Tarzoq . Generally the subtitle needs to be synced with voice signals rather than with another subtitle. I have also seen people using visual signals in limited scenarios, e.g., syncing subtitles with the lip movements in a video clip featuring a news presenter. Unless you have a machine-translated subtitle where the words match exactly with those in the out-of-sync subtitle, this is often not the case in real-world situations. The following syncing options using subaligner are language-agnostic (i.e., the language of the subtitle can be different from the language of the video/audio) and I think you might want to give it a go (or probably have already):
`subaligner -m single -v video.mp4 -s subtitle.srt`
`subaligner -m dual -v video.mp4 -s subtitle.srt`

Thanks. Your feedback is greatly appreciated, and it motivate us to continue improving the tool.

**Comment by tarzoq** [comment]
Good to know, thank you for the quick reply! Today though I sadly ran into an issue where the extraction of the audio from video got cancelled because it reached the "Timeout". This happened while running in a docker container on my Unraid-server, where smaller video worked flawlessly. The same video and subtitle that didn't work on the server worked fine on a different more powerful computer running Docker Desktop in Windows. (If you need to know specs for these computers please let me know)

I was wondering if this is caused by generally slower hardware and if it is possible to increase the said Timeout.

**Comment by baxtree** [comment]
Yes, it is possible. Assuming your timeout issue was related to processing of media files (I can't see error logs to verify this), I have made it possible to customise its value via the CLI. Please try checking out the master branch and running `pip install -e .` Then you can pass in your timeout value using either the `--media_process_timeout` or `-mpt` option. For example:

`subaligner -m dual -v video.mp4 -s subtitle.srt -mpt 300    # The default media process timeout is 180 seconds`

**Comment by tarzoq** [comment]
Thanks a lot sir, I'm very impressed with you fixing my issue on such short notice. I'm happy to confirm that it now works as intended!

Not to burden you with any more work but I noticed another problem regarding special characters and the stretch function. Basically special characters like é, á, — etc turn into Ã©, Ã¡, â€” respectively which turned sentences like "This is not détente." into -> "This is not dÃ©tente.". This only happened when running with -so (--stretch_on) and occurred no matter what movie and subtitle-file was used. The pattern also remained in both Linux and Windows which rules out filesystems. 

Weirdly enough special characters didn't change only if the special characters were either in the same sentence or in sentences right next to one another.

Thanks in advance!

**Comment by baxtree** [comment]
Glad it works for your use case.

I cannot replicate the error on accented characters on my machine so I reckon the auto-detection on the encoding of your subtitle file somehow failed and later defaulted to UTF-8. Can you please pull the master branch again and check the content of `output.srt` after running the following cmd?

`subaligner -m dual -v tests/subaligner/resource/test.mp4 -s tests/subaligner/resource/accented.srt -o output.srt -so`

**Comment by tarzoq** [comment]
Ran the tests and it worked for me too. I'm sorry, maybe I should've been more specific before. The special characters remained unchanged as long as they were in the same sentence or in adjacent sentences. The problem at least for me could be replicated with a regular English subtitle with a special character like "é" thrown somewhere in there, just as long as they aren't right next to each other or in the same part of the subtitle.

Hopefully you can also replicate the problem so it's not just an error on my side, good luck!

**Comment by baxtree** [comment]
No worries. Do you mind sharing your subtitle file? Or just a partial snippet long enough to replay the error will be helpful.

**Comment by tarzoq** [comment]
Sure, I haven't modified it since I'm not to knowledgeable about text encoding and if I would mess something up. Keep in mind, this is just one of the subtitles I saw this problem with. Also, note how far between the different special characters are to each other.

[OriginalSubtitle.zip](https://github.com/user-attachments/files/15904558/OriginalSubtitle.zip)

**Comment by baxtree** [comment]
Your file has been encoded with UTF-8. I ran the synchronisation on it against a video of similar duration and the output doesn't show any special characters such as Ã© ...Weird. It may be worth checking the default encoding used by your shell/OS with `locale`. Try setting the env vars if they are not using UTF8, e.g.:
```
apt-get update
apt-get install locales
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
Also, is it possible to install subaligner on your host OS instead of using a Docker container and see how that behaves?

**Comment by tarzoq** [comment]
I'm using Bazarr (subtitle downloader) which automatically converts the subtitles downloaded to UTF-8, would this mean that Subaligner wouldn't work alongside Bazarr? I'm confused, which text encoding should be used with Subaligner? 

I'll try going native on Linux.

**Comment by baxtree** [comment]
Subaligner will try to detect the encoding of the subtitle file passed in and use the same encoding for the output file. If the detection fails, it will use UTF-8 as the default.

**Comment by tarzoq** [comment]
I just tried running it natively on Linux after making sure all system locale was set to UTF-8 and, no luck. I tried a different subtitle from a different source which using the "file -i" command also was UTF-8, which sadly turned out no different.

I'm curious, I have put together a zip file containing a non-DMCA movie along with the original subtitles and my aligned subtitles from running `subaligner -m dual -v The\ Last\ Man\ on\ Earth\ \(1964\)\ Bluray-1080p.mp4 -s The\ Last\ Man\ on\ Earth\ \(1964\)\ Bluray-1080p.en.srt -o Failed.srt -so`.

`0:36:21 & 0:45:37 & 1:25:25` are the following timestamps where I added accented characters, which in the "Failed.srt" turned into  Ã©, Ã¡ and so on.

If your computer manages to align the subtitles without changing any characters I'll be baffled!

https://drive.google.com/file/d/1XU_uuT7CjrC81V4vUqNBQBeCCsKJeRim/view?usp=sharing

**Comment by baxtree** [comment]
Hi, @Tarzoq Can you check my access request?

**Comment by tarzoq** [comment]
Should work now. Sorry, I thought I made sure everyone had access. 😅

**Comment by baxtree** [comment]
You are right, and now I can see "Let's gÃ©t to work" with `-so` present. The root cause is the encoding detector mistook intermediate files, generated by the stretcher and encoded in UTF-8, for ISO-8859-1. The detector uses heuristics so there is a chance for it to misfunction. I've checked in a fix and please give it a go. Thanks for your assistance in troubleshooting.

**Comment by tarzoq** [comment]
I'm happy to report that it now seems to be working exactly as it should. This issue really got me scratching my head so I'm glad it's been sorted out. Thanks again for your patience and cooperation, I haven't stumbled upon any other problems so I now deem this issue closed. Cheers!
